title: Darshan

logo: /assets/img/logo.jpg
# email: TODO
blank_title: true
favicon: true
description: ""
show_downloads: false
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  # - jekyll-sitemap
  # - jekyll-seo-tag
  # - jemoji
  - jekyll-remote-theme

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/darshanrampatel
  - name: Stack Overflow
    icon: <i class="fa-brands fa-stack-overflow"></i>
    link: https://stackoverflow.com/users/5024969/darshan
  - name: Last.fm
    icon: <i class="fa-brands fa-lastfm"></i>
    link: https://www.last.fm/user/darshanpatel

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
