title: Darshan

logo: /assets/img/logo.jpg
# email: TODO
blank_title: false
favicon: true
description: ""
show_downloads: false
remote_theme: BDHU/minimalist
color-scheme: dark
plugins:
  # - jekyll-sitemap
  # - jekyll-seo-tag
  # - jemoji
  - jekyll-remote-theme

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    colour: "58a6ff"
    link: https://github.com/darshanrampatel
  - name: Last.fm
    icon: <i class="fa-brands fa-lastfm"></i>
    colour: "d51007"
    link: https://www.last.fm/user/darshanpatel
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    colour: "0077b5"
    link: https://www.linkedin.com/in/darshanrampatel


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
